name: commons_flutter
description: commons_flutter
version: 1.0.0
homepage: https://sokomishalov.github.io/about-me/
author: sokomishalov <sokomishalov@mail.ru>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  commons_dart:
    path: ../commons_dart

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
